name = "line-bot-worker"

account_id = "8319e2d1771176a18cb30db84028d6c5"
workers_dev = true
compatibility_date = "2024-05-10"
compatibility_flags = ["nodejs_compat"]

main = "index.js"

[observability.logs]
enabled = true